#pragma once


#ifdef __cplusplus
extern "C" {
#endif

const char *const KEYWORDS =
	"IF if ЕСЛИ если\n"
	"THEN then ТОГДА тогда\n"
	"ELSEIF elseif ИНАЧЕЕСЛИ иначеесли\n"
	"ELSE else ИНАЧЕ иначе\n"
	"ENDIF endif КОНЕЦЕСЛИ конецесли\n"
	"\n"
	"FOR for ДЛЯ для\n"
	"EACH each КАЖДОГО каждого\n"
	"IN in ИЗ из\n"
	"TO to ПО по\n"
	"WHILE while ПОКА пока\n"
	"DO do ЦИКЛ цикл\n"
	"ENDDO enddo КОНЕЦЦИКЛА конеццикла\n"
	"\n"
	"PROCEDURE procedure ПРОЦЕДУРА процедура\n"
	"FUNCTION function ФУНКЦИЯ функция\n"
	"ENDPROCEDURE endprocedure КОНЕЦПРОЦЕДУРЫ конецпроцедуры\n"
	"ENDFUNCTION endfunction КОНЕЦФУНКЦИИ конецфункции\n"
	"\n"
	"VAR var ПЕРЕМ перем\n"
	"GOTO goto ПЕРЕЙТИ перейти\n"
	"RETURN return ВОЗВРАТ возврат\n"
	"CONTINUE continue ПРОДОЛЖИТЬ продолжить\n"
	"BREAK break ПРЕРВАТЬ прервать\n"
	"\n"
	"AND and И и\n"
	"OR or ИЛИ или\n"
	"NOT not НЕ не\n"
	"\n"
	"TRY try ПОПЫТКА попытка\n"
	"EXCEPT except ИСКЛЮЧЕНИЕ исключение\n"
	"RAISE raise ВЫЗВАТЬИСКЛЮЧЕНИЕ вызватьисключение\n"
	"ENDTRY endtry КОНЕЦПОПЫТКИ конецпопытки\n"
	"NEW new НОВЫЙ новый\n"
	"EXECUTE execute ВЫПОЛНИТЬ выполнить\n"
	"ADDHANDLER addhandler ДОБАВИТЬОБРАБОТЧИК добавитьобработчик\n"
	"REMOVEHANDLER removehandler УДАЛИТЬОБРАБОТЧИК удалитьобработчик\n"
	"\n"
	"NULL null NULL null\n"
	"BOOLEAN boolean БУЛЕВО булево\n"
	"TRUE true ИСТИНА истина\n"
	"FALSE false ЛОЖЬ ложь\n"
	"DATE date ДАТА дата\n"
	"NUMBER number ЧИСЛО число\n"
	"STRING string СТРОКА строка\n"
	"UNDEFINED undefined НЕОПРЕДЕЛЕНО неопределено\n"
	"TYPE type ТИП тип\n"
	"TYPEOF typeof ТИПЗНЧ типзнч\n"
	"\n"
	"EXPORT export ЭКСПОРТ экспорт\n"
	"VAL val ЗНАЧ знач\n"
	"\n"
	"SERVER server СЕРВЕР сервер\n"
	"ATSERVER atserver НАСЕРВЕРЕ насервере\n"
	"CLIENT client КЛИЕНТ клиент\n"
	"ATCLIENT atclient НАКЛИЕНТЕ наклиенте\n"
	"THINCLIENT thinclient ТОНКИЙКЛИЕНТ тонкийклиент\n"
	"WEBCLIENT webclient ВЕБКЛИЕНТ вебклиент\n"
	"EXTERNALCONNECTION externalconnection ВНЕШНЕЕСОЕДИЕНИЕ внешнеесоединение\n"
	"THICKCLIENTMANAGEDAPPLICATION thichclientmanagedapplication ТОЛСТЫЙКЛИЕНТУПРАВЛЯЕМОЕПРИЛОЖЕНИЕ толстыйклиентуправляемоеприложение\n"
	"THICHCLIENTORDINARYAPPLICATION thickclientordinaryapplication ТОЛСТЫЙКЛИЕНТОБЫЧНОЕПРИЛОЖЕНИЕ толстыйклиентобычноеприложение\n"
	"ATSERVERWITHOUTCONTEXT atserverwithoutcontext НАСЕРВЕРЕБЕЗКОНТЕКСТА насерверебезконтекста\n"
	"ATCLIENTATSERVER atclientatserver НАКЛИЕНТЕНАСЕРВЕРЕ наклиентенасервере\n"
	"ATCLIENTATSERVERWITHOUTCONTEXT atclientatserverwithoutcontext НАКЛИЕНТЕНАСЕРВЕРЕБЕЗКОНТЕКСТА наклиентенасерверебезконтекста\n"
	"REGION region ОБЛАСТЬ область\n"
	"ENDREGION endregion КОНЕЦОБЛАСТИ конецобласти\n"

#ifdef __cplusplus
} /* extern "C" */
#endif